#!/usr/bin/python3.8
# #coding:u8

"""
Challenge : create a function called parseToRoman which, for a given number, will return its value in Roman numerals.
"""

roman_numbers_list = [
	"M", 	# 1000
	"D", 	# 500
	"CD",	# 400
	"C", 	# 100
	"XC",	# 90
	"L", 	# 50
	"XL",	# 40
	"X", 	# 10
	"IX", 	# 9
	"V",	# 5
	"IV",	# 4
	"I", 	# 1
]

arabic_numbers_list = [
	1000,
	500,
	400,
	100,
	90,
	50,
	40,
	10,
	9,
	5,
	4,
	1,
]

def parse_to_roman(arabic_number):

	roman_number = ""

	for indice in range(len(arabic_numbers_list)):
		while arabic_number >= arabic_numbers_list[indice]:
			if arabic_number - arabic_numbers_list[indice] >= 0:
				arabic_number -= arabic_numbers_list[indice]
				roman_number += roman_numbers_list [indice]

	return roman_number
			

number = int(input("Enter a number : "))
print(parse_to_roman(number))
